global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "nexusai-platform"
    environment: "production"

scrape_configs:
  - job_name: "nexusai-gateway"
    static_configs:
      - targets: ["gateway:8000"]
    metrics_path: /metrics

  - job_name: "nexusai-brain-tumor"
    static_configs:
      - targets: ["brain-tumor-service:8001"]
    metrics_path: /metrics

  - job_name: "nexusai-retina"
    static_configs:
      - targets: ["retina-service:8002"]
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
